import { useRouter } from 'next/router'
import Link from 'next/link'
import Head from 'next/head'
import {
  Layout,
  theme,
  Typography,
  Space,
  Button,
  Badge,
  Dropdown,
} from 'antd'
import {
  ShoppingCartOutlined,
  LoginOutlined,
  LogoutOutlined,
  FileDoneOutlined,
} from '@ant-design/icons'
import { HookSwr } from '@/lib/hooks/HookSwr'
import Cookies from 'js-cookie'

const { Title } = Typography
const { Header, Content } = Layout

const LayoutApp = ({ children, isMobile }) => {
  const isLogin = Cookies.get('token_user')
  const router = useRouter()
  const { data: userDetail, isLoading } = HookSwr({
    path: '/user/me',
  })
  const { data: cart } = HookSwr({
    path: '/pesanan/cart/count',
    revalidate: true,
  })
  const {
    token: { colorBgContainer, paddingMD },
  } = theme.useToken()

  const onMenuClick = ({ key }) => {
    router.push({ pathname: `/${key}` })
  }

  const items = [
    {
      key: 'pesanan',
      label: (
        <Space>
          <FileDoneOutlined />
          Pesanan
        </Space>
      ),
    },
    {
      key: 'logout',
      label: (
        <Space>
          <LogoutOutlined />
          Logout
        </Space>
      ),
    },
  ]

  return (
    <>
      <Head>
        <title>E-Commerce App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout
        style={{
          height: '100vh',
          width: '100%',
        }}
      >
        <Layout>
          <Header
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              padding: paddingMD,
              background: colorBgContainer,
            }}
          >
            <Title style={{ margin: 0, padding: 0 }} level={4}>
              <Link href="/" style={{ color: 'black' }}>
                E-COMMERCE
              </Link>
            </Title>
            <Space size="middle">
              <Badge count={cart?.data} showZero>
                <Button
                  icon={<ShoppingCartOutlined />}
                  onClick={() =>
                    router.push({ pathname: '/keranjang' })
                  }
                />
              </Badge>
              {!isLogin ? (
                <Button
                  icon={<LoginOutlined />}
                  onClick={() => router.push({ pathname: '/login' })}
                >
                  Masuk
                </Button>
              ) : (
                <Dropdown.Button
                  size="middle"
                  loading={isLoading}
                  menu={{
                    items,
                    onClick: onMenuClick,
                  }}
                >
                  {!isMobile ? userDetail?.data?.email : ''}
                </Dropdown.Button>
              )}
            </Space>
          </Header>
          <Content
            className="content-dashboard"
            style={{
              overflowY: 'scroll',
              padding: paddingMD,
            }}
          >
            {children}
          </Content>
        </Layout>
      </Layout>
    </>
  )
}
export default LayoutApp
